/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package speex_aec;

public class SpeexAecJNI {

  static {
    try {
        java.lang.System.loadLibrary("speex");
        java.lang.System.loadLibrary("speex_aec");
    } catch (UnsatisfiedLinkError e) {
        java.lang.System.err.println("native code library failed to load.\n" + e);
        java.lang.System.exit(1);
    }
  }

  public final static native void open(int jarg2, int jarg3, int jarg4);
  public final static native void close();
  public final static native void process(short[] jarg2, short[] jarg3, short[] jarg4);
}
