/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package speex_aec;

public class SpeexAec {
  public static void open(int sampleRate, int bufsize, int totalSize) {
    SpeexAecJNI.open(sampleRate, bufsize, totalSize);
  }

  public static void close() {
    SpeexAecJNI.close();
  }

  public static void process(short[] inbuf, short[] refbuf, short[] outbuf) {
    SpeexAecJNI.process(inbuf, refbuf, outbuf);
  }

}
